const {enemyTeams} = require('./Config/jsonOptions'); 
const fs = require('fs');

const newDictionary = []; 
const myNames = [];

const trainerMap = {
  "Rival Gary - Pallet Town (Bulbasuar)": "Rival Gary Venusaur Pallet Town",
  "Rival Gary - Pallet Town (Charmander)": "Rival Gary Charizard Pallet Town",
  "Rival Gary - Pallet Town (Squirtle)": "Rival Gary Blastoise Pallet Town",
  "(Optional) Gary - Route 22 (Bulbasuar)": "Rival Gary Venusaur Route 22",
  "(Optional) Gary - Route 22 (Charmander)": "Rival Gary Charizard Route 22",
  "(Optional) Gary - Route 22 (Squirtle)": "Rival Gary Blastoise Route 22",
  "Brendan - Viridian Forest": "Brendan Viridian Forest",
  "lass Anne": "lass Anne Route 2",
  "Catcher Sammy": "Bug Catcher Sammy Viridian Forest",
  "Falkner": "Johto Gym Leader Falkner Pewter City",
  "Brock": "Leader Brock Pewter City",
  "Lass Sally": "Lass Sally Route 3",
  "Super Nerd Miguel": "Fossil Maniac Miguel Mt. Moon",
  "Archer - Mt. Moon": "Team Rocket Admin Archer Mt. Moon",
  "Gary - Cerulean City (Bulbasuar)": "Rival Gary Venusaur Cerulean City",
  "Gary - Cerulean City (Charmander)": "Rival Gary Charizard Cerulean City",
  "Gary - Cerulean City (Squirtle)": "Rival Gary Blastoise Cerulean City",
  "Catcher Cale": "Bug Catcher Cale Route 24",
  "Lass Ali": "Lass Ali Route 24",
  "Youngster Timmy": "Youngster Timmy Route 24",
  // "Lass Reli": "Lass Reli Route 24",
  "Camper Ethan": "Camper Ethan Route 24",
  "Rocket Grunt - Nugget Bridge": "Nugget Bridge Rocket Grunt Route 24",
  "(Optional) Bugsy (Pre-Surge)": "Johto Leader Bugsy Route 25",
  "(Optional) Bugsy (Post-Surge)": "Johto Leader Bugsy Route 25 Post Surge",
  "Misty": "Leader Misty Cerulean City",
  "Rocket Grunt - Dig House": "Back of Dig House Rocket Grunt Cerulean City",
  "Camper Jeff": "Camper Jeff Route 6",
  "Lass Ann": "Lass Anne S.S. Anne", 
  "Gentleman Brooks": "Gentleman Brooks S.S. Anne",
  "Sailor Edmond" : "Sailor Edmond S.S. Anne",
  "Sailor Trevor": "Sailor Trevor S.S. Anne",
  "Brendan - S.S Anne": "Brendan S.S. Anne",
  "(Optional) Whitney": "Leader Whitney Route 11",
  "Gentleman Tucker": "Gentleman Tucker S.S. Anne",
  "Lt. Surge": "Leader Lt. Surge S.S. Anne",
  "Picknicker Alicia": "Picnicker Alicia Route 9",
  "Picknicker Caitlin": "Picnicker Caitlin Route 9",
  "Picknicker Dana": "Picnicker Dana Rock Tunnel",
  "Maniac Herman": "PokeManiac Herman Route 10",
  "(Optional) Morty": "Leader Morty Lavender Town",
  "Super Nerd Aidan": "Super Nerd Aidan Route 10",
  "Ace Mary": "Ace Trainer Mary Route 10",
  "Erika": "Leader Erika Celadon City",
  "Game Corner Guard": "Guard Game Corner",
  "Rocket Left Guard": "Left Guard Game Corner",
  "Rocket Right Guard": "Right Guard Game Corner",
  "Giovanni - Rocket Hideout": "Boss Giovanni Team Rocket Hideout",
  "Channeler Ruth": "Channeler Ruth Pokemon Tower",
  "Ghost": "Ghost Pokemon Tower",
  "Rocket Grunt 1 - Pokemon Tower": "Team Rocket Grunt 1 Pokemon Tower",
  "Rocket Grunt 2 - Pokemon Tower": "Team Rocket Grunt 2 Pokemon Tower",
  "Rocket Grunt 3 - Pokemon Tower": "Team Rocket Grunt 3 Pokemon Tower",
  "Gary - Silph Co. (Bulbasuar)": "Rival Gary Venusaur Silph Co",
  "Gary - Silph Co. (Charmander)": "Rival Gary Charizard Silph Co",
  "Gary - Silph Co. (Squirtle)": "Rival Gary Blastoise Silph Co",
  "Ariana - Silph Co.": "Team Rocket Executive Ariana - Silph Co.",
  "Archer - Silph Co.": "Team Rocket Executive Archer Silph Co",
  "Brendan - Silph Co.": "Brendan Silph Co",
  "Giovanni - Silph Co.": "Boss Giovanni Silph Co",
  "(Optional) Ace Cole": "Ace Trainer Cole Route 12",
  "(Optional) Beauty Sam": "Beauty Sam Route 15",
  "(Optional) Beauty Shelly": "Beauty Shelly Route 15",
  "(Optional) Chuck": "Leader Chuck Saffron City",
  "Sabrina": "Leader Sabrina Saffron City",
  "(Optional) Dumass Kid": "Dumass Kid Saffron City",
  "Rocker Luca": "Rocker Luca Route 12",
  "Camper Justin": "Camper Justin Route 12",
  "Fisherman Andrew": "Fisherman Andrew Route 12",
  "Bird Keeper Sebastian": "Bird Keeper Sebastian Route 13",
  "Picknicker Susie": "Picknicker Susie Route 13",
  "Picknicker Alma": "Picknicker Alma Route 13",
  "Beauty Lola": "Beauty Lola Route 13",
  "Beauty Sheila": "Beauty Sheila Route 13",
  "Bird Keeper Perry": "Bird Keeper Perry Route 14",
  "Biker Jared": "Biker Jared Route 14",
  "Bird Keeper Robert": "Bird Keeper Robert Route 14",
  "(Optional) Ace Haley": "Ace Trainer Haley Route 14",
  "Biker Lao": "Biker Lao Route 15",
  "Cue Ball Koji": "Cue Ball Koji Route 16",
  "Cue Ball Luke": "Cue Ball Luke Route 16",
  "Biker Ruben": "Biker Ruben Route 17",
  "Cue Ball Camron": "Cue Ball Camron Route 17",
  "Biker Hideo": "Biker Hideo Route 17",
  "Biker William": "Biker William Route 17",
  "Bird Keeper Jacob": "Bird Keeper Jacob Route 18",
  "(Optional) Tamer Ramiro": "Tamer Ramiro Safari Zone",
  "Ace Wilton": "Ace Trainer Wilton Route 15",
  "Brendan - Safari Zone": "Brendan Safari Zone",
  "Brock (Rematch)": "Leader Brock Rematch",
  "Misty (Rematch)": "Leader Misty Rematch",
  "Lt. Surge (Rematch)": "Leader Lt Surge Rematch",
  "(Optional) Erika (Rematch)": "Leader Erika Rematch",
  "Juggler Kayden": "Juggler Kayden Fuchsia City",
  "Koga": "Leader Koga Fuchsia City",
  "(Optional) Dumass Jojo Fan": "Dumass Jojo Fan Power Plant",
  "(Optional) Pryce - Team 1": "Leader Pryce 1 Seafoam Islands",
  "(Optional) Pryce - Team 2": "Leader Pryce 2 Seafoam Islands",
  "May": "May Cinnabar Island",
  "(Optional) Jasmine": "Leader Jasmine Cinnabar Island",
  "(Optional) Scientist Ted": "Scientist Ted Mansion",
  "Burglar Lewis": "Burglar Lewis Mansion",
  "Ace Derek": "Ace Trainer Derek Route 21",
  "Ace Lucy": "Ace Trainer Lucy Route 21",
  "Ace Zac": "Ace Trainer Zac Route 21",
  "Blaine": "Leader Blaine Cinnabar Island",
  "Rocket Grunt 1 - Cerulean Cave": "Team Rocket Grunt 1 Cerulean Cave",
  "Rocket Grunt 2 - Cerulean Cave": "Team Rocket Grunt 2 Cerulean Cave",
  "Archer - Cerulean Cave": "Team Rocket Executive Archer Cerulean Cave",
  "Ariana - Cerulean Cave": "Team Rocket Executive Ariana Cerulean Cave",
  "Giovanni - Cerulean Cave": "Boss Giovanni Cerulean Cave",
  "Lance - Cerulean Cave": "Lance Cerulean Cave",
  "(Optional) Black Belt Ketchup": "Black Belt Ketchup Mt. Ember",
  "(Optional) Black Belt Ketchup (Rematch)": "Black Belt Ketchup Mt. Ember",
  "Clair": "Leader Clair Indigo Plateau",
  "(Optional) Burglar Max": "Burglar Max Cinnabar Island",
  "(Optional) Burglar Anson": "Burglar Anson Cinnabar Island",
  "Gary - Route 22 (Bulbasuar)": "Rival Gary Venusaur Route 22 Late",
  "Gary - Route 22 (Charmander)": "Rival Gary Charizard Route 22 Late",
  "Gary - Route 22 (Squirtle)": "Rival Gary Blastoise Route 22 Late",
  "Brendan - Route 23": "Brendan Route 23",
  "Ace Naomi": "Ace Trainer Naomi Victory Road",
  "Ace Rolando": "Ace Trainer Rolando Victory Road",
  "Ace George": "Ace Trainer George Victory Road",
  "Ace Caroline": "Ace Trainer Caroline Victory Road",
  "Ace Colby": "Ace Trainer Colby Victory Road",
  "Ace Alexa": "Ace Trainer Alexa Victory Road",
  "Ace Trainer Ray" : "Ace Ray Victory Road", 
  "Ace Trainer Tyra": "Ace Tyra Victory Road",
  "Dumass Creator": "Dumass Creator Victory Road",
  "Lorelei - Team 1": "Lorelei 1 Pokemon League",
  "Lorelei - Team 2": "Lorelei 2 Pokemon League",
  "Bruno - Team 1": "Bruno 1 Pokemon League",
  "Bruno - Team 2": "Bruno 2 Pokemon League",
  "Agatha - Team 1": "Agatha 1 Pokemon League",
  "Agatha - Team 2": "Agatha 2 Pokemon League",
  "Lance - Team 1": "Lance 1 Pokemon League",
  "Lance - Team 2": "Lance 2 Pokemon League",
  "Gary - Champion (Bulbasuar)": "Rival Gary Venusaur Pokemon League",
  "Gary - Champion (Charmander)": "Rival Gary Charizard Pokemon League",
  "Gary - Champion (Squirtle)": "Rival Gary Blastoise Pokemon League"
};

for (const [trainerName, team] of Object.entries(enemyTeams)) {
    newDictionary.push(trainerName);
}

for (const key of Object.keys(trainerMap)) {
    myNames.push(key);
}

fs.writeFileSync('./Models/trainerNames.json', JSON.stringify(newDictionary, null, 2), 'utf8');
fs.writeFileSync('./Models/myTrainerNames.json', JSON.stringify(myNames, null, 2), 'utf8');
