const bannedMoves = {
    'Aqua Step': '', 
    'Fell Stinger': '', 
    'Flame Charge': '', 
    'Power-Up Punch': '', 
    'Scale Shot': '', 
    'Skull Bash': '', 
    'Trailblaze': '', 
    'Chilly Reception': '', 
    'Electric Terrain': '', 
    'Grassy Terrain': '', 
    'Misty Terrain': '', 
    'Psychic Terrain': '', 
    'Rain Dance': '', 
    'Sandstorm': '', 
    'Snowscape': '', 
    'Sunny Day': '', 
    'Trick Ro': '', 
    'Charge Beam': '', 
    'Electro Shot': '', 
    'Esper Wing': '', 
    'Fiery Dance': '', 
    'Meteor Beam': '', 
    'Spit Up': '', 
    'Torch Song': '', 
    'Spikes': '', 
    'Stealth Rock': '', 
    'Sticky Web': '', 
    'Toxic Spikes': '', 
    'Acid Armor': '', 
    'Agility': '', 
    'Amnesia': '', 
    'Autotomize': '', 
    'Barrier': '', 
    'Belly Drum': '', 
    'Bulk Up': '', 
    'Calm Mind': '', 
    'Clangorous Soul': '', 
    'Coaching': '', 
    'Coil': '', 
    'Cosmic Power': '', 
    'Cotton Guard': '', 
    'Curse': '', 
    'Defense Curl': '', 
    'Dragon Dance': '', 
    'Fillet Away': '', 
    'Geomancy': '', 
    'Growth': '', 
    'Harden': '', 
    'Hone Claws': '', 
    'Howl': '', 
    'Iron Defense': '', 
    'Meditate': '', 
    'Nasty Plot': '', 
    'No Retreat': '', 
    'Quiver Dance': '', 
    'Rock Polish': '', 
    'Shell Smash': '', 
    'Shift Gear': '', 
    'Stockpile': '', 
    'Swallow': '', 
    'Swords Dance': '', 
    'Tail Glow': '', 
    'Tailwind': '', 
    'Tidy Up': '', 
    'Victory Dance': '', 
    'Withdraw': '', 
    'Work Up': '', 
    'Charm': '', 
    'Court Change': '', 
    'Decorate': '', 
    'Destiny Bond': '', 
    'Leech Seed': '', 
    'Magic Coat': '', 
    'Perish Song': '', 
    'Powder': '', 
    'Protect': '', 
    'Psych Up': '', 
    'Shed Tail': '', 
    'Snatch': '', 
    'Strength Sap': '', 
    'Substitute': '', 
    'Taunt': '', 
    'Toxic': '', 
    'Wide Guard': ''
}

const leechSeedExceptions = {
    'Maractus': '', 
    'Shiinotic': '', 
    'Cherrim': '', 
    'Eldegoss': '', 
    'Carnivine': '', 
    'Abomasnow': '', 
    'Victreebel': '', 
    'Serperior': '', 
    'Meganium': '', 
    'Lilligant': ''
}; 

const toxicExceptions = {
    'Maractus': '', 
    'Shiinotic': '', 
    'Cherrim': '', 
    'Eldegoss': '', 
    'Carnivine': '', 
    'Abomasnow': '', 
    'Victreebel': '',
    'Serperior': '',
    'Lilligant': '',
    'Butterfree': '',
    'Sudowoodo': '',
    'Bastiodon': '',
    'Raticate': '',
    'Magcargo': '',
    'Wormadam': '',
    'Garbodor': '',
    'Minior-Core': '',
    'Raticate-A': '',
    'Shuckle': '',
    'Mothim': '',
    'Swanna': '',
    'Komala': '',
    'Wigglytuff': '',
    'Corsola': '',
    'Pachirisu': '',
    'Vanilluxe': '',
    'Greedent': '',
    'Parasect': '',
    'Mightyena': '',
    'Emolga': '',
    'Thievul': '',
    'Venomoth': '',
    'Linoone': '',
    'Purugly': '',
    'Beheeyem': '',
    'Dugtrio': '',
    'Beautifly': '',
    'Skuntank': '',
    'Cryogonal': '',
    'Dubwool': '',
    'Dugtrio-A': '',
    'Dustox': '',
    'Chatot': '',
    'Stunfisk': '',
    'Coalossal': '',
    'Persian': '',
    'Grumpig': '',
    'Stunfisk-G': '',
    'Stonjourner': '',
    'Persian-A': '',
    'Spinda': '',
    'Lumineon': '',
    'Druddigon': '',
    'Pincurchin': '',
    'Vileplume': '',
    'Castform': '',
    'Vivillon': '',
    'Eiscue': '',
    'Bellossom': '',
    'Kecleon': '',
    'Phione': '',
    'Furfrou': '',
    'Indeedee-M': '',
    'Luvdisc': '',
    'Slurpuff': '',
    'Indeedee-F': '',
    'Farfetch\'d': '',
    'Masquerain': '',
    'Musharna': '',
    'Malamar': '',
    'Oinkologne': '',
    'Muk': '',
    'Wailord': '',
    'Watchog': '',
    'Dedenne': '',
    'Spidops': '',
    'Ninetales': '',
    'Probopass': '',
    'Liepard': '',
    'Carbink': '',
    'Rabsca': '',
    'Hypno': '',
    'Delcatty': '',
    'Unfezant': '',
    'Gumshoos': '',
    'Mr. Mime': '',
    'Swalot': '',
    'Gigalith': '',
    'Oricorio': '',
    'Bibarel': '',
    'Swoobat': '',
    'Ribombee': '',
    'Ariados': '',
    'Kricketune': '',
    'Lurantis': ''
};

module.exports = { bannedMoves, leechSeedExceptions, toxicExceptions }; 